### ISSUE TITLE
Deploy script uwsgi issue

### ISSUE THREAD

**Issue by tp-l** [LexPredict/lexpredict-contraxsuite-deploy#6] opened 2017-10-22 08:50 UTC
Hi

I've ran the setup_local.sh script  on a clean Ubuntu 16.04.03 VM with the script finishing by displaying the error "contrax_uwsgi.service not found  (uwsgi.log.txt)

From the install log, it appears uwsgi-2.0.14 has successfully installed.  However the script did not create a contrax_uwsgi.ini file.  When the file wasn't present I tried copying templates/uwsgi.ini to etc/uwsgi./contrax_uwsgi.ini, without success (and assume the template needs editing to be correct)

Any assistance would be greatly appreciated

**Comment by reddalexx** [comment] 2017-10-22 11:03
Hi
This is fixed in 1.0.2 branch,
but right now you can use some commands to install .ini file:
- firstly you should be under activated virtual environment, I'm assuming that you already have it,
just `source ve/bin/activate` should activate it
- then run fabric command to install .ini for uwsgi:
`fab -c local/fabricrc upload_template_and_reload:uwsgi`
- and then run uwsgi:
`sudo systemctl restart contrax_uwsgi`
this should do the trick

**Comment by mjbommar** [comment] 2017-11-01 12:02
Hello @tp-l, did @reddalexx's comments help you resolve this?

**Comment by tp-l** [comment] 2017-11-02 01:07
Hi @mjbommar and thanks @reddalexx.

@reddalexx's comments did get the service started, but unfortunately I couldn't get the system working.

I've subsequently tried running a new clean install with the 1.0.2 branch.  The uWSGI (and other services) appear to install correctly, but the script is failing with errors prior to completion.

I see the 1.0.3 branch is now available - I'll try this in the next couple of days and see whether I have more luck.

Thanks again

**Comment by mjbommar** [comment] 2017-11-02 01:09
OK, thanks for the update.  Were you running the script as a `root` user by any chance, or were you running as a non-root user like `ubuntu`?

**Comment by tp-l** [comment] 2017-11-02 01:16
used a non-root user with sudo privileges (ran as the same user as included/updated in `local/fabricrc`)

**Comment by tp-l** [comment] 2017-11-22 00:26
Hi,
Confirming I'm still having a failure with the 1.0.3 branch install, but no longer with uWSGI.  

The script gets to nearly the end, but fails with an undefined DEBUG_SQL exception (during celery setup).    Do you know what might be causing this?
Thanks

**Comment by skprasadu** [comment] 2017-11-25 02:37
I also get similar error almost for lost of ending steps, as follows, let me know if you get the solution:

[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out:     if DEBUG_SQL:
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: NameError: name 'DEBUG_SQL' is not defined
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: 	> celery2@ip-172-31-23-195: * Child terminated with exit code 1
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out: [1;31mFAILED[0m
[ec2-52-89-107-244.us-west-2.compute.amazonaws.com] out:

**Comment by reddalexx** [comment] 2018-01-16 17:06
@tp-l @skprasadu - In both of these cases we see the same issue: for some reason local_settings.py was not uploaded to target instance and uwsgi application throws errors because it cannot find some variables from there.

----------------
upload_templates
----------------
[localhost] put: <file obj> -> /home/##user##/run.sh
[localhost] put: <file obj> -> /usr/share/nginx/html/502.html
[localhost] put: <file obj> -> /etc/systemd/system/contrax_uwsgi.service
[localhost] put: <file obj> -> /etc/uwsgi/contrax_uwsgi.ini
Disconnecting from localhost... done.
So, you should repeat all steps described above.

We've not been able to reproduce this issue on AWS or other environments after trying numerous times. We're considering refactoring the setup & installation a bit. What approach would be preferred for you?

One thought we had is that perhaps we can change the first command from
fab -c local/fabricrc upload_templates
to upload only local_settings.py:
fab -c local/fabricrc upload_template_and_reload:settings
and then proceed with other commands to complete installation

**Closed by reddalexx** 2018-01-16 17:06 UTC
